---
- hosts: run
  roles:
    - role: ansible-docker-deployment
      vars:
        docker_deployment_project_name: odh-mentor-otp-run
        docker_deployment_release_name: '{{ release_name }}'
        docker_deployment_release_files:
          - local: ../docker-compose.run.run.yml
            remote: docker-compose.yml
          - local: ../../.env
            remote: .env
        docker_deployment_aws_ecr_repository: 755952719952.dkr.ecr.eu-west-1.amazonaws.com
        docker_deployment_execution_type: app
