version: "3.4"

services:
  journey:
    image: ${DOCKER_IMAGE_JOURNEY}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/journey/Dockerfile
      args:
        - API_HOST=${API_HOST}
        - API_PORT=${API_PORT}
        - API_PATH=${API_PATH}
        - GEOCODER_BASEURL=${GEOCODER_BASEURL}
        - PARKING_BASEURL=${PARKING_BASEURL}
        - CHARGER_BASEURL=${CHARGER_BASEURL}
        - CARSHARING_BASEURL=${CARSHARING_BASEURL}
  otp:
    image: ${DOCKER_IMAGE_OTP}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/otp/Dockerfile
  gbfs:
    image: ${DOCKER_IMAGE_GBFS}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/gbfs/Dockerfile
  geocoder:
    image: ${DOCKER_IMAGE_GEOCODER}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/geocoder/Dockerfile
  carsharing:
    image: ${DOCKER_IMAGE_CARSHARING}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/carsharing/Dockerfile
  parking:
    image: ${DOCKER_IMAGE_PARKING}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/parking/Dockerfile
  charger:
    image: ${DOCKER_IMAGE_ECHARGING}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/charger/Dockerfile

